language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '14'
install: npm install
before_install:
  - npm install -g npm@7
  - npm install -g greenkeeper-lockfile@2
jobs:
  include:
    - stage: test
      script:
        - npm run compile
        - npm run lint
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload
    - stage: deploy
      if: branch = master
      script: npm run travis-deploy-once "npm run semantic-release"
